version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  # test:
  #   docker:
  #     - image: circleci/node:14
  #   steps:
  #     - checkout
  #     - run:
  #         name: Install Dependencies
  #         command: npm install
  #     - run:
  #         name: Run Tests
  #         command: npm test

  deploy:
    machine: true
    working_directory: ~/be-project/
    steps:
      - checkout
      - run:
          name: Deploy to EC2
          command: |
            echo $(pwd)
            echo $(ls)
            cd /home/circleci/project
            echo $(pwd)
            echo $(ls)

workflows:
  version: 2
  deploy:
    jobs:
      # - test
      - deploy:
          # requires:
          #   - test
          filters:
            branches:
              only:
                - main
#            ssh -oStrictHostKeyChecking=no -v $USER@$DNS "./deploy.sh"

