version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  # test:
  #   docker:
  #     - image: circleci/node:14
  #   steps:
  #     - checkout
  #     - run:
  #         name: Install Dependencies
  #         command: npm install
  #     - run:
  #         name: Run Tests
  #         command: npm test

  deploy:
    docker:
      - image: circleci/python:3.8  # Thay đổi hình ảnh Docker tùy theo yêu cầu của bạn
    steps:
      - checkout
      - run:
          name: Deploy to EC2
          command: |
            echo "Deploying to EC2..."
            ssh -oStrictHostKeyChecking=no -v $USER@$DNS "./deploy.sh"

workflows:
  version: 2
  deploy:
    jobs:
      # - test
      - deploy:
          # requires:
          #   - test
          filters:
            branches:
              only:
                - main

